# Generated by Django 6.1.1 on 2026-09-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(db_index=True, max_length=50, verbose_name='Корневая директория')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='Под-директория (slug)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Директория изображений',
                'verbose_name_plural': 'Директории изображений',
                'ordering': ['-year', 'slug'],
                'indexes': [models.Index(fields=['year', 'slug'], name='wagtail_ima_year_4ee44a_idx')],
                'constraints': [models.UniqueConstraint(fields=('year', 'slug'), name='unique_image_directory')],
            },
        ),
    ]
